exports.all_customers = [
    {
        id: 1,
        name: "Customer A",
        username: "customer_a",
        email: "customer_a@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, A street, Address",
        contact: "+971 50 000 0000",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 2,
        name: "Customer B",
        username: "customer_b",
        email: "customer_b@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, B street, Address",
        contact: "+971 50 111 1111",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 3,
        name: "Customer C",
        username: "customer_c",
        email: "customer_c@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, C street, Address",
        contact: "+971 50 222 2222",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 4,
        name: "Customer D",
        username: "customer_d",
        email: "customer_d@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, D street, Address",
        contact: "+971 50 333 3333",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 5,
        name: "Customer E",
        username: "customer_e",
        email: "customer_e@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, E street, Address",
        contact: "+971 50 444 4444",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 6,
        name: "Customer F",
        username: "customer_f",
        email: "customer_f@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, F street, Address",
        contact: "+971 50 555 5555",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 7,
        name: "Customer G",
        username: "customer_g",
        email: "customer_f@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, G street, Address",
        contact: "+971 50 666 6666",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
    {
        id: 8,
        name: "Customer H",
        username: "customer_h",
        email: "customer_h@mail.com",
        age: 33,
        gender: "male",
        address: "Customer, H street, Address",
        contact: "+971 50 777 7777",
        avatar: "http://localhost:3001/images/customer/customer.png",
    },
];
